### PR TITLE
Fix focus and key up + down on first toggle

### LINKED ISSUE #91: Arrow up/down doesn't work on initial docs toggling
When opening the docs the first time and without any selection of a list item, you cannot navigate using the up/down arrow keys. Using the right arrow key works.

### PR DESCRIPTION
**Pull request by Huvik**
Fixes #91.

### CODE REVIEW

File: packages/graphql-playground-react/src/components/Playground/DocExplorer/GraphDocs.tsx [hunk 1]
```diff
@@ -224,43 +224,39 @@ class GraphDocs extends React.Component<
...
+            {schema && (
+              <RootColumn
+                schema={schema}
+                width={this.state.widthMap.root || columnWidth - 1}
+                searchValue={this.state.searchValue}
+                handleSearch={this.handleSearch}
+                sessionId={this.props.sessionId}
+              />
+            )}
+            {navStack.map((stack, index) => (
```
Comment (timsuchanek) [inline packages/graphql-playground-react/src/components/Playground/DocExplorer/GraphDocs.tsx]: Please add `!emptySchema` again, otherwise the column will incorrectly be rendered after deserialization, when there is not yet a schema
