### PR TITLE
Fixed link to documentation type broken

### LINKED ISSUE #495: Type Link in Autocomplete Dropdown broken.
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

OsX Safari
OsX Chrome

#### What steps may we take to reproduce the behavior?
Click on the type definition in the autocomplete dropdown menus. Then you get a blank page with only the dropdown remaining. Refreshing the tab clears the issue, but it can be triggered again by clicking the type again.

I would expect that clicking the type opens a new tab or forwards to the full type definition or maybe expands the schema sidenav. 

bildschirmfoto 2018-01-15 um 10 49 58

_Please provide a gif or image of the issue for a quicker response/fix._

### PR DESCRIPTION
**Pull request by Weakky**
Fixes #495.

Changes proposed in this pull request:

Links shown at the bottom of the autocomplete dropdown were crashing the app everytime.
It should now be fixed, opening the schema explorer everytime we click the links.
The `navStack` is reseted, showing only one tab with the documentation of the type only.

I removed all references to `docExplorerOpen` as it was dead code coming from the original GraphiQL component.

Some tests would be very welcome !

capture d ecran 2018-01-22 a 15 56 02

### CODE REVIEW

File: packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx [hunk 1]
```diff
@@ -626,6 +623,11 @@ export class GraphQLEditor extends React.PureComponent<
           </div>
         </div>
         <GraphDocs
+          ref={(ref: any) => {
```
Comment (timsuchanek) [inline packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx]: Please transform this inline arrow function to a method, due to performance.

**Comment by Weakky** [comment]
Fixed. Any reasons why the test aren't succeeding ?

**Comment by timsuchanek** [comment]
Thanks for fixing!! Yes, the reason is just that the yarn workspaces have problems in circle. You could pull the latest master into your branch to fix this, but as you didn't change anything in the electron app, I'll just merge it.
