### PR TITLE
Fixing interfaces and unions in docs

### LINKED ISSUE #322: Docs: Interface/union type not displayed properly
Interfaces and unions are currently displayed as a normal `type` definition. That's a bug.

## Example

This is the actual schema definition of the following schema:

```graphql
# Represents an owner of a Repository.
interface RepositoryOwner {
  # A URL pointing to the owner's public avatar.
  avatarUrl(
    # The size of the resulting square image.
    size: Int
  ): URI!
  id: ID!

  # The username used to login.
  login: String!

  # A list of repositories this user has pinned to their profile
  pinnedRepositories(
    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the last _n_ elements from the list.
    last: Int

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # If non-null, filters repositories according to privacy
    privacy: RepositoryPrivacy

    # Ordering options for repositories returned from the connection
    orderBy: RepositoryOrder

    # Affiliation options for repositories returned from the connection
    affiliations: [RepositoryAffiliation]

    # If non-null, filters repositories according to whether they have been locked
    isLocked: Boolean
  ): RepositoryConnection!

  # A list of repositories that the user owns.
  repositories(
    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the last _n_ elements from the list.
    last: Int

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # If non-null, filters repositories according to privacy
    privacy: RepositoryPrivacy

    # Ordering options for repositories returned from the connection
    orderBy: RepositoryOrder

    # Affiliation options for repositories returned from the connection
    affiliations: [RepositoryAffiliation]

    # If non-null, filters repositories according to whether they have been locked
    isLocked: Boolean

    # If non-null, filters repositories according to whether they are forks of another repository
    isFork: Boolean
  ): RepositoryConnection!

  # Find Repository.
  repository(
    # Name of Repository to find.
    name: String!
  ): Repository

  # The HTTP URL for the owner.
  resourcePath: URI!

  # The HTTP URL for the owner.
  url: URI!
}

```

image

### PR DESCRIPTION
**Pull request by Huvik**
Fixes #322 #171.

Changes proposed in this pull request:

Added link to unions, renamed details for enums etc and added interfaces

### CODE REVIEW

File: packages/graphql-playground-react/src/components/Playground/DocExplorer/FieldDoc.tsx [hunk 1]
```diff
@@ -53,6 +58,13 @@ export default class FieldDoc extends React.Component<Props, State> {
     const implementationsOffset =
       obj.fields.length + obj.interfaces.length + obj.args.length
 
+    const typeInstance =
```
Comment (Huvik) [inline packages/graphql-playground-react/src/components/Playground/DocExplorer/FieldDoc.tsx]: I am not happy this style of coding but was trying to follow lint rules. I can change it to something like this:
``` js
if (type instanceof GraphQLInterfaceType) {
  typeInstance = 'interface'
} else if (type instanceof GraphQLUnionType) {
  typeInstance = 'union'
} else if (type instanceof GraphQLEnumType) {
  typeInstance = 'enum'
} else {
  typeInstance = 'type'
}
```
What looks better in my eyes

Comment (timsuchanek) [reply packages/graphql-playground-react/src/components/Playground/DocExplorer/FieldDoc.tsx]: Yes, that look definitely better! You can also identify that linting rule and ignore it in the tslint config.
I already had a lot of cases where this rule forced you to do this ugly ternary stuff.
